### PR TITLE
Add expire methods

### PR DESCRIPTION
**Pull request by whiteforestzx**
Hi! Added several additional EXPIRE methods to lib

### CODE REVIEW

**Comment by git-hulk** [comment]
@whiteforestzx Is it better to group them into one function like `ExpireWithOption(ctx context.Context, key string, expiration time.Duration, option ExpireOption)`?

**Comment by whiteforestzx** [comment]
@git-hulk I suppose it's bot, but I'll answer anyway - such grouping will broke consistency with `go-redis`, so no.

**Comment by git-hulk** [comment]
@whiteforestzx Thank you! It makes sense to keep consistent with go-redis. And I'm not a bot 😆 ..

**Review by git-hulk — APPROVED** [review]

**Comment by whiteforestzx** [comment]
@git-hulk oh, oops, I'm sorry. It's all because of git prefix... Embarrassing. 🙈

**Comment by git-hulk** [comment]
> @git-hulk oh, oops, I'm sorry. It's all because of git prefix... Embarrassing. 🙈

Aha, that’s fun.

**Pull request merged**
